INSERT INTO tb_product (name, description, price) VALUES ('AKB48 Official Lightstick Neo 7th Generation', 'O mais recente lightstick oficial do AKB48, com 16 cores de LED e um design ergonômico. Essencial para qualquer show.', 45.00);
INSERT INTO tb_product (name, description, price) VALUES ('Photocard Set - Heavy Rotation (3-pack)', 'Conjunto de 3 photocards aleatórios dos membros da seleção do single icônico "Heavy Rotation".', 8.50);
INSERT INTO tb_product (name, description, price) VALUES ('Poster Oficial - 64th Single "Hisashiburi no Lip Gloss"', 'Poster oficial do 64º single do grupo, "Hisashiburi no Lip Gloss". Tamanho B2.', 12.00);
INSERT INTO tb_product (name, description, price) VALUES ('Album - "Kamikyokutachi" (Edição Regular)', 'A coletânea de grandes sucessos do AKB48, "Kamikyokutachi", em sua edição regular com CD.', 30.00);
INSERT INTO tb_product (name, description, price) VALUES ('Toalha Oshimen - Yui Oguri', 'Mostre seu apoio para Yui Oguri com esta toalha de concerto apresentando seu nome e as cores do time.', 22.00);
INSERT INTO tb_product (name, description, price) VALUES ('Chaveiro de Acrílico - Logotipo do Teatro AKB48', 'Chaveiro de acrílico com o logotipo icônico do Teatro AKB48 em Akihabara.', 7.00);
INSERT INTO tb_product (name, description, price) VALUES ('Camiseta do 17º Aniversário do Teatro AKB48', 'Camiseta de edição limitada comemorando o 17º aniversário do Teatro AKB48. Tamanho G.', 35.00);
INSERT INTO tb_product (name, description, price) VALUES ('Photocard Set - Koisuru Fortune Cookie (3-pack)', 'Conjunto de 3 photocards aleatórios dos membros da seleção do single de sucesso "Koisuru Fortune Cookie".', 8.50);
INSERT INTO tb_product (name, description, price) VALUES ('Blu-ray - AKB48 Request Hour Set List Best 100 2023', 'Gravação em alta definição do show "Request Hour Set List Best 100" de 2023. Inclui bastidores.', 75.00);
INSERT INTO tb_product (name, description, price) VALUES ('Happi Coat Oficial do AKB48 (Rosa)', 'Happi coat tradicional japonês com o logotipo do AKB48. Perfeito para eventos e festivais.', 55.00);
INSERT INTO tb_product (name, description, price) VALUES ('Photobook de Graduação de Yuki Kashiwagi', 'Um photobook especial celebrando a longa e ilustre carreira de Yuki Kashiwagi no AKB48.', 40.00);
INSERT INTO tb_product (name, description, price) VALUES ('Pasta de Arquivos A4 - Team A', 'Pasta de arquivos tamanho A4 com uma foto promocional do Team A.', 6.00);
INSERT INTO tb_product (name, description, price) VALUES ('Album - "1830m" (Edição de Teatro)', 'O álbum de estúdio "1830m" na sua versão de teatro, com uma capa alternativa.', 25.00);
INSERT INTO tb_product (name, description, price) VALUES ('Poster - Eleição Geral Senbatsu de 2018', 'Poster comemorativo da Eleição Geral Senbatsu de 2018, apresentando os membros mais votados.', 15.00);
INSERT INTO tb_product (name, description, price) VALUES ('Conjunto de Emblemas de Lata (5-pack)', 'Um conjunto de 5 emblemas de lata aleatórios com fotos de membros de diferentes times.', 10.00);
INSERT INTO tb_product (name, description, price) VALUES ('AKB48 Official Lightstick - Team K Version', 'Um lightstick especial com a cor verde representativa do Team K.', 40.00);
INSERT INTO tb_product (name, description, price) VALUES ('Photocard Set - Oogoe Diamond (3-pack)', 'Conjunto de 3 photocards aleatórios dos membros da seleção do single "Oogoe Diamond".', 9.00);
INSERT INTO tb_product (name, description, price) VALUES ('Toalha Oshimen - Hitomi Honda', 'Mostre seu apoio para Hitomi Honda com esta toalha de concerto apresentando seu nome e as cores do time.', 22.00);
INSERT INTO tb_product (name, description, price) VALUES ('Chaveiro de Acrílico - Mascote Oficial "Akbee"', 'Chaveiro de acrílico apresentando o mascote fofo do AKB48, "Akbee".', 7.50);
INSERT INTO tb_product (name, description, price) VALUES ('Camiseta com Logotipo Clássico do AKB48 (Preta)', 'Camiseta preta de algodão com o logotipo clássico do AKB48 no peito. Tamanho M.', 30.00);
INSERT INTO tb_product (name, description, price) VALUES ('Single - "RIVER" (Type A, CD+DVD)', 'A versão Type A do single "RIVER", inclui um DVD com o videoclipe e conteúdo bônus.', 18.00);
INSERT INTO tb_product (name, description, price) VALUES ('Pasta de Arquivos A4 - Team K', 'Pasta de arquivos tamanho A4 com uma foto promocional do Team K.', 6.00);
INSERT INTO tb_product (name, description, price) VALUES ('AKB48 Calendário de Parede Oficial 2026', 'Calendário de parede para 2026 com fotos impressionantes dos membros do AKB48 para cada mês.', 25.00);
INSERT INTO tb_product (name, description, price) VALUES ('Photocard Binder Oficial do AKB48', 'Um fichário para colecionar e proteger seus preciosos photocards do AKB48.', 20.00);
INSERT INTO tb_product (name, description, price) VALUES ('Sacola Ecológica do AKB48', 'Sacola ecológica reutilizável com um design simples e elegante do logotipo do AKB48.', 15.00);
INSERT INTO tb_product (name, description, price) VALUES ('AKB48 Official Lightstick - Team B Version', 'Um lightstick especial com a cor azul representativa do Team B.', 40.00);
INSERT INTO tb_product (name, description, price) VALUES ('Photocard Set - Ponytail to Shushu (3-pack)', 'Conjunto de 3 photocards aleatórios dos membros da seleção do single de verão "Ponytail to Shushu".', 8.50);
INSERT INTO tb_product (name, description, price) VALUES ('Toalha Oshimen - Erina Oda', 'Mostre seu apoio para Erina Oda com esta toalha de concerto apresentando seu nome e as cores do time.', 22.00);
INSERT INTO tb_product (name, description, price) VALUES ('Chaveiro com Uniforme em Miniatura', 'Chaveiro com uma réplica em miniatura de um dos icônicos uniformes de palco do AKB48.', 10.00);
INSERT INTO tb_product (name, description, price) VALUES ('Moletom com Capuz do AKB48 (Cinza)', 'Moletom com capuz confortável e estiloso com o logotipo do AKB48 bordado. Tamanho G.', 60.00);
INSERT INTO tb_product (name, description, price) VALUES ('Album - "Koko ni Ita Koto" (Edição Limitada)', 'Edição limitada do álbum "Koko ni Ita Koto" com um photobook bônus.', 45.00);
INSERT INTO tb_product (name, description, price) VALUES ('Pasta de Arquivos A4 - Team B', 'Pasta de arquivos tamanho A4 com uma foto promocional do Team B.', 6.00);
INSERT INTO tb_product (name, description, price) VALUES ('DVD - Show de Graduação de Minami Takahashi', 'Gravação completa do emocionante show de graduação da ex-Gerente Geral Minami Takahashi.', 70.00);
INSERT INTO tb_product (name, description, price) VALUES ('Livro de Coleção de Posters da Eleição Geral', 'Um livro de alta qualidade compilando os posters de campanha de todos os membros de uma Eleição Geral Senbatsu.', 35.00);
INSERT INTO tb_product (name, description, price) VALUES ('Leque de Mão (Uchiwa) - Mion Mukaichi', 'Leque de mão com uma foto de Mion Mukaichi, perfeito para se refrescar durante os shows.', 8.00);
INSERT INTO tb_product (name, description, price) VALUES ('AKB48 Official Lightstick - Team 4 Version', 'Um lightstick especial com a cor amarela representativa do Team 4.', 40.00);
INSERT INTO tb_product (name, description, price) VALUES ('Photocard Set - Gingham Check (3-pack)', 'Conjunto de 3 photocards aleatórios dos membros da seleção do single "Gingham Check".', 8.50);
INSERT INTO tb_product (name, description, price) VALUES ('Toalha Oshimen - Narumi Kuranoo', 'Mostre seu apoio para Narumi Kuranoo com esta toalha de concerto apresentando seu nome e as cores do time.', 22.00);
INSERT INTO tb_product (name, description, price) VALUES ('Suporte de Acrílico - Yui Oguri', 'Suporte de acrílico de mesa com uma foto de corpo inteiro de Yui Oguri.', 15.00);
INSERT INTO tb_product (name, description, price) VALUES ('Boné de Beisebol do AKB48', 'Boné de beisebol preto com o logotipo do AKB48 bordado em rosa.', 28.00);
INSERT INTO tb_product (name, description, price) VALUES ('Single - "Aitakatta" (Edição Remasterizada)', 'O single de estreia major "Aitakatta" em uma edição remasterizada com qualidade de áudio aprimorada.', 15.00);
INSERT INTO tb_product (name, description, price) VALUES ('Pasta de Arquivos A4 - Team 4', 'Pasta de arquivos tamanho A4 com uma foto promocional do Team 4.', 6.00);
INSERT INTO tb_product (name, description, price) VALUES ('Chaveiro do Material do Piso do Palco do Teatro AKB48', 'Um chaveiro de edição de colecionador contendo um pedaço real do antigo piso do palco do Teatro AKB48.', 50.00);
INSERT INTO tb_product (name, description, price) VALUES ('Caneca do AKB48 Cafe & Shop', 'Caneca de cerâmica oficial do AKB48 Cafe & Shop em Akihabara.', 18.00);
INSERT INTO tb_product (name, description, price) VALUES ('Pulseira de Silicone do AKB48', 'Pulseira de silicone rosa com o logotipo do AKB48 gravado.', 5.00);
INSERT INTO tb_product (name, description, price) VALUES ('AKB48 Official Lightstick - Team 8 Version', 'Um lightstick especial com um design representando o Team 8 e suas prefeituras.', 42.00);
INSERT INTO tb_product (name, description, price) VALUES ('Photocard Set - #Sukinanda (3-pack)', 'Conjunto de 3 photocards aleatórios dos membros da seleção do single "#Sukinanda".', 8.50);
INSERT INTO tb_product (name, description, price) VALUES ('Toalha Oshimen - Rin Okabe', 'Mostre seu apoio para Rin Okabe com esta toalha de concerto apresentando seu nome e as cores do time.', 22.00);
INSERT INTO tb_product (name, description, price) VALUES ('Suporte de Acrílico - Hitomi Honda', 'Suporte de acrílico de mesa com uma foto de corpo inteiro de Hitomi Honda.', 15.00);
INSERT INTO tb_product (name, description, price) VALUES ('Conjunto de Adesivos do AKB48', 'Uma folha de adesivos com vários logotipos do AKB48, mascotes e fotos de membros em estilo chibi.', 6.50);